import os

# Quart-Auth Settings
QUART_AUTH_COOKIE_DOMAIN=os.environ.get('SERVER_NAME')
QUART_AUTH_COOKIE_PATH="/"
QUART_AUTH_COOKIE_HTTP_ONLY=True
QUART_AUTH_COOKIE_SAMESITE="Lax"
QUART_AUTH_COOKIE_SECURE=True
# QUART_AUTH_DURATION=365 * 24 * 60 * 60
QUART_AUTH_DURATION=7 * 3 * 30 * 30
QUART_AUTH_MODE="cookie"

# Quart-wtf Settings
WTF_CSRF_ENABLED=True
WTF_CSRF_CHECK_DEFAULT=True
WTF_CSRF_METHODS=['POST', 'PUT', 'PATCH', 'DELETE']
WTF_CSRF_FIELD_NAME="csrf_token"
WTF_CSRF_HEADERS=['X-CSRFToken', 'X-CSRF-Token']
WTF_CSRF_TIME_LIMIT=3600
WTF_CSRF_SSL_STRICT=True
WTF_I18N_ENABLED=False

#CSRF Settings
SESSION_COOKIE_DOMAIN=os.environ.get('SERVER_NAME')

# Quart Rate Limiter Settings
QUART_RATE_LIMITER_ENABLED=True